### ISSUE TITLE
ground:db 1.0.0 - error grounding Meteor.users

### ISSUE THREAD

**Issue by markshust** [Meteor-Community-Packages/ground-db#129]
I'm trying to ground Meteor.users as your README says:

`Ground.Collection(Meteor.users);`

However, I'm receiving the following error:

`Error: First argument to new Mongo.Collection must be a string or null`

**Comment by tagrudev** [comment]
The last version of ground:db is 0.3.14, can you be more specific where and on what occasion this happens? Some code would be nice too.

**Comment by raix** [comment]
@markoshust do you mean the `1.0.0-alpha.1`? (it's still very early days for this eta approx january 2016)

**Comment by markoshust** [comment]
yes -- the 1.0.0 version (alpha).

**Comment by raix** [comment]
@markoshust you get no promises or documentation on alpha :)
*(reason why it's not working is that the alpha is actually extending the Mongo.Collection class - where the current version attaches it self making it a bit more flexible)*

**Comment by markoshust** [comment]
Not asking for any promises, just filing a bug with 1.0.0 --- unless you don't want us to file any bugs against that version :)

**Comment by raix** [comment]
issues are fine :)

**Comment by Lenin7** [comment]
Is he eta still January 2016? 
Thanks

**Comment by marbemac** [comment]
@raix Also interested in the ETA, or general state of the project, as we need to use websql or indexed db (something with a higher storage cap than 10mb). Is the alpha working ok right now for simple things (we only use grounddb for offline collections, no re-sync etc)?

**Comment by KoenLav** [comment]
The alpha seems to work fine here. Collections are available offline and outstanding changes are sent to the server when the connection is re-established. Changes made on other clients during the offline period are also synchronized after re-establishing the connection.

I'm just getting one error: 'Cannot call a class as a function' on line 65 of babel-runtime.js. It's caused by GroundDB, but what's strange is that it only appears once (even though we're grounding multiple collections).
