### ISSUE TITLE
DB insert does not return in offline mode.

### ISSUE THREAD

**Issue by spgandhi** [Meteor-Community-Packages/ground-db#159]
I am building an app using angular meteor. I have installed appcache and ground:db to make the app work in offline mode.

The app has products and users can add products to cart and then place the order. In the offline mode all the past products and orders display properly. 

To insert new order, below is the code I am using - 

`Orders.insert(order, function(err, record){`
`if(err)`
    `toastr.error(err.reason, 'Error');`
`else{`
    `toastr.success('Order Created!', 'Success');`
    `$rootScope.order = {};`
    `$location.path('/orders/'+record);`
`}`

According to the code, either success message or error message should be displayed, but none of them is displayed. And the interesting thing is if I go back, then the order is actually added to the local database and when connected to internet it is synced with live database.

Is there some configuration settings that I am missing?

My Collections are defined as below - 

`Orders = new Mongo.Collection('orders');
Products = new Mongo.Collection('products');
Options = new Mongo.Collection('options');

Ground.Collection(Meteor.users) 

Ground.Collection(Orders, { connection: null });
Ground.Collection(Products, { connection: null });
Ground.Collection(Options, { connection: null });
`

**Comment by introrse** [comment]
Database method callbacks don't (really, can't) work in offline mode because there is no way to durably store a function reference.  

There are 3 cases to think about: At best, in online mode, you get the callback after the server has processed the method.  When slightly delayed, you may still get a callback on reconnect if your app hasn't been unloaded in the intervening time.  And if a larger amount of time elapses and you reconnect after the app has been unloaded GroundDB does forward the queued methods to the server, but it has no way to invoke the callbacks. 

When we adopted GroundDB we had to stop using DB callbacks entirely.

**Comment by raix** [comment]
I've released `2.0.0-alpha.1` [Notes about the new version, migration and what it doesn't do](https://github.com/GroundMeteor/db/issues/153#issuecomment-206125703) - The new version is a cache only - it will not try to reason about method calls
